version: 2.1
orbs:
  windows: circleci/windows@2.2.0
jobs:
  build:
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Build Application"
          working_directory: ./src/
          command: dotnet build --configuration Release
  test:
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Restore NuGet Packages"
          working_directory: ./src/
          command: dotnet restore
      - run:
          name: "Run Tests"
          working_directory: ./src/
          command: dotnet test
workflows:
  diffengine-ci-pipeline:
    jobs:
      - build
      - test:
          requires:
            - build
