version: 2.1
orbs:
  windows: circleci/windows@2.2.0
jobs:
  build:
   docker:
      - image: mcr.microsoft.com/dotnet/sdk:9.0
    steps:
      - checkout
      - run:
          name: Restore
          working_directory: ./src/
          command: dotnet restore
      - run:
          name: "Build Application"
          working_directory: ./src/
          command: dotnet build --configuration Release
  test:
     docker:
      - image: mcr.microsoft.com/dotnet/sdk:9.0
    steps:
      - checkout
      - run:
          name: "Restore NuGet Packages"
          working_directory: ./src/DiffEngine.Tests
          command: dotnet restore
      - run:
          name: "Run Tests"
          working_directory: ./src/DiffEngine.Tests
          command: dotnet test
workflows:
  diffengine-ci-pipeline:
    jobs:
      - build
      - test:
          requires:
            - build
