version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:9.0
    steps:
      - checkout
      - run:
          name: Restore
          working_directory: ./src/
          command: dotnet restore -p:EnableWindowsTargeting=true
      - run:
          name: "Build Application"
          working_directory: ./src/
          command: dotnet build --configuration Release -p:EnableWindowsTargeting=true

  test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:9.0
    steps:
      - checkout
      - run:
          name: "Restore NuGet Packages"
          working_directory: ./src/DiffEngine.Tests
          command: dotnet restore
      - run:
          name: "Run Tests"
          working_directory: ./src/DiffEngine.Tests
          command: dotnet test -p:EnableWindowsTargeting=true

workflows:
  diffengine-ci-pipeline:
    jobs:
      - build
      - test:
          requires:
            - build
